targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
      # Allows the code generator to target files outside of the lib folder
      - integration_test/**
      - test/**
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # auto register any class with a name matches the given pattern
          class_name_pattern:
            "Service$|RepositoryImpl$|Bloc$|Cubit$|DataSourceImpl$|Mapper|UseCase$|Client$"
          # auto register any class inside a file with a
          # name matches the given pattern
          file_name_pattern: "_cubit$"
      bdd_widget_test|featureBuilder:
        options:
          includeIntegrationTestBinding: true # if false, integration test will not include binding; default is true
          stepFolderName: step # this trick is required to share steps between widget and integration tests
          # testMethodName: customTestMethodName
#          include: package:bdd_widget_test/bdd_options.yaml # you may add defaul external steps with this line
          externalSteps:                                    # or list only steps that you need
            - package:bdd_widget_test/step/i_see_text.dart
            # - package:bdd_widget_test/step/i_dont_see_text.dart
            # - package:bdd_widget_test/step/i_see_multiple_texts.dart
            # - package:bdd_widget_test/step/i_tap_text.dart
            # - package:bdd_widget_test/step/i_see_icon.dart
            # - package:bdd_widget_test/step/i_dont_see_icon.dart
            # - package:bdd_widget_test/step/i_tap_icon.dart
            # - package:bdd_widget_test/step/i_see_rich_text.dart
            # - package:bdd_widget_test/step/i_dont_see_rich_text.dart
            # - package:bdd_widget_test/step/i_see_widget.dart
            # - package:bdd_widget_test/step/i_dont_see_widget.dart
            # - package:bdd_widget_test/step/i_see_exactly_widgets.dart
            # - package:bdd_widget_test/step/i_see_multiple_widgets.dart
            # - package:bdd_widget_test/step/i_enter_into_input_field.dart
            # - package:bdd_widget_test/step/i_see_disabled_elevated_button.dart
            # - package:bdd_widget_test/step/i_see_enabled_elevated_button.dart
            # - package:bdd_widget_test/step/i_wait.dart
            # - package:bdd_widget_test/step/i_dismiss_the_page.dart
        generate_for:
          - test/**
          - integration_test/**